/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasibookingtiket;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author ASUS
 */
public class DetailTheBox extends javax.swing.JFrame {
     String film, hari,tanggal, jam,harga;
     public static javax.swing.JTextField tf_jam;

    /**
     * Creates new form DetailTheBox
     */
    public DetailTheBox() {
        initComponents();
        // center form 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        button_tb_senin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        button_tb_selasa = new javax.swing.JButton();
        button_tb_rabu = new javax.swing.JButton();
        button_tb_kamis = new javax.swing.JButton();
        button_tb_jumat = new javax.swing.JButton();
        button_tb_sabtu = new javax.swing.JButton();
        button_tb_minggu = new javax.swing.JButton();
        judul6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 42)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("THE BOX");

        minimize.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(293, 392));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/tb.jpg"))); // NOI18N
        jLabel8.setText("jLabel2");
        jLabel8.setPreferredSize(new java.awt.Dimension(293, 392));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        button_tb_senin.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_senin.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_senin.setText("Senin, 2021-06-21 15:00");
        button_tb_senin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_seninMouseClicked(evt);
            }
        });
        button_tb_senin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_seninActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Screenwriter \n& Director : Yang Jung Woong\nStars      : Park Chan Yeol, \n             Jo Dal Hwan, \nDuration : 94 minutes\nRating   : R (Remaja)\nGenre    : Action, Sci-fi, Thriller\n\nDua legenda beradu dalam “Godzilla vs. Kong” \nsaat musuh mitis ini bertemu dalam pertempuran \nspektakuler selama berabad-abad, dengan nasib \ndunia tergantung pada keseimbangan. \nKong dan para pelindungnya melakukan perjalanan \nberbahaya untuk menemukan rumahnya yang sebenarnya,\n dan bersama mereka adalah Jia, \nseorang gadis yatim piatu yang dengannya dia telah \nmembentuk ikatan yang unik dan kuat. \nTapi mereka tiba-tiba menemukan diri mereka di jalur\nGodzilla yang marah, menyebabkan petak kehancuran \ndi seluruh dunia. Bentrokan epik antara dua raksasa \nitu — yang dipicu oleh kekuatan tak terlihat — \nhanyalah awal dari misteri yang terletak jauh di \ndalam inti Bumi.\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        button_tb_selasa.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_selasa.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_selasa.setText("Selasa, 2021-06-22 15:00");
        button_tb_selasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_selasaMouseClicked(evt);
            }
        });
        button_tb_selasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_selasaActionPerformed(evt);
            }
        });

        button_tb_rabu.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_rabu.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_rabu.setText("Rabu, 2021-06-23 15:00");
        button_tb_rabu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_rabuMouseClicked(evt);
            }
        });
        button_tb_rabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_rabuActionPerformed(evt);
            }
        });

        button_tb_kamis.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_kamis.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_kamis.setText("Kamis, 2021-06-24 15:00");
        button_tb_kamis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_kamisMouseClicked(evt);
            }
        });
        button_tb_kamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_kamisActionPerformed(evt);
            }
        });

        button_tb_jumat.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_jumat.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_jumat.setText("Jumat, 2021-06-25 15:00");
        button_tb_jumat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_jumatMouseClicked(evt);
            }
        });
        button_tb_jumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_jumatActionPerformed(evt);
            }
        });

        button_tb_sabtu.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_sabtu.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_sabtu.setText("Sabtu, 2021-06-26 15:00");
        button_tb_sabtu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_sabtuMouseClicked(evt);
            }
        });
        button_tb_sabtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_sabtuActionPerformed(evt);
            }
        });

        button_tb_minggu.setBackground(new java.awt.Color(204, 204, 204));
        button_tb_minggu.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        button_tb_minggu.setText("Minggu, 2021-06-27 15:00");
        button_tb_minggu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tb_mingguMouseClicked(evt);
            }
        });
        button_tb_minggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tb_mingguActionPerformed(evt);
            }
        });

        judul6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel36.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel36.setText("SENIN-KAMIS               JUMAT          SABTU-MINGGU");

        jLabel37.setBackground(new java.awt.Color(0, 255, 102));
        jLabel37.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel37.setText("       40.000                          50.000                         65.000");

        javax.swing.GroupLayout judul6Layout = new javax.swing.GroupLayout(judul6);
        judul6.setLayout(judul6Layout);
        judul6Layout.setHorizontalGroup(
            judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(judul6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36)))
        );
        judul6Layout.setVerticalGroup(
            judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul6Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_tb_minggu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_tb_rabu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_tb_jumat, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_tb_sabtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_tb_kamis, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_tb_senin, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_tb_selasa, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(judul6, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close))
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_tb_senin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tb_selasa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_tb_rabu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tb_kamis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_tb_sabtu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tb_jumat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_tb_minggu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void button_tb_seninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_seninMouseClicked

    }//GEN-LAST:event_button_tb_seninMouseClicked

    private void button_tb_seninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_seninActionPerformed
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Senin";
        tanggal="2021-06-21";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_seninActionPerformed

    private void button_tb_selasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_selasaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_tb_selasaMouseClicked

    private void button_tb_selasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_selasaActionPerformed
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Selasa";
        tanggal="2021-06-22";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_selasaActionPerformed

    private void button_tb_rabuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_rabuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_tb_rabuMouseClicked

    private void button_tb_rabuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_rabuActionPerformed
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Rabu";
        tanggal="2021-06-23";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_rabuActionPerformed

    private void button_tb_kamisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_kamisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_tb_kamisMouseClicked

    private void button_tb_kamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_kamisActionPerformed
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Kamis";
        tanggal="2021-06-24";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_kamisActionPerformed

    private void button_tb_jumatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_jumatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_tb_jumatMouseClicked

    private void button_tb_jumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_jumatActionPerformed
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Jumat";
        tanggal="2021-06-25";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_jumatActionPerformed

    private void button_tb_sabtuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_sabtuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_tb_sabtuMouseClicked

    private void button_tb_sabtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_sabtuActionPerformed
       KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Sabtu";
        tanggal="2021-06-26";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_sabtuActionPerformed

    private void button_tb_mingguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tb_mingguMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_tb_mingguMouseClicked

    private void button_tb_mingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tb_mingguActionPerformed
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Minggu";
        tanggal="2021-06-27";
        jam="15:00";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
    }//GEN-LAST:event_button_tb_mingguActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTheBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton button_tb_jumat;
    public static javax.swing.JButton button_tb_kamis;
    public static javax.swing.JButton button_tb_minggu;
    public static javax.swing.JButton button_tb_rabu;
    public static javax.swing.JButton button_tb_sabtu;
    public static javax.swing.JButton button_tb_selasa;
    public static javax.swing.JButton button_tb_senin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel judul6;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
