/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasibookingtiket;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;


/**
 *
 * @author ASUS
 */
public class DetailGodzilla extends javax.swing.JFrame {
    String film, hari,tanggal, jam,harga;
    public static javax.swing.JTextField tf_jam;
    public static javax.swing.JTextField tf_harga;
    
    /**
     * Creates new form DetailGodzilla
     */
    public DetailGodzilla() {
        initComponents();
        // center form 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        buttongodzillasenin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        judul6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        buttongodzillaselasa = new javax.swing.JButton();
        buttongodzillarabu = new javax.swing.JButton();
        buttongodzillakamis = new javax.swing.JButton();
        buttongodzillajumat = new javax.swing.JButton();
        buttongodzillasabtu = new javax.swing.JButton();
        buttongodzillaminggu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 42)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GODZILLA VS KONG");

        minimize.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasibookingtiket/Godzilla vs_ Kong (2021)(1).png"))); // NOI18N
        jLabel13.setText("jLabel1");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttongodzillasenin.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillasenin.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillasenin.setText("Senin, 2021-06-21 12:00");
        buttongodzillasenin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillaseninMouseClicked(evt);
            }
        });
        buttongodzillasenin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillaseninActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Director : Adam Wingard\nWriters  : Terry Rossio (story by), \n           Michael Dougherty (story by)\nStars    : Alexander Skarsgård, \n           Millie Bobby Brown, \n           Rebecca Hall\nDuration : 113 minutes\nRating   : R (Remaja)\nGenre    : Action, Sci-fi, Thriller\n\nDua legenda beradu dalam “Godzilla vs. Kong” \nsaat musuh mitis ini bertemu dalam pertempuran \nspektakuler selama berabad-abad, dengan nasib \ndunia tergantung pada keseimbangan. \nKong dan para pelindungnya melakukan perjalanan \nberbahaya untuk menemukan rumahnya yang sebenarnya,\n dan bersama mereka adalah Jia, \nseorang gadis yatim piatu yang dengannya dia telah \nmembentuk ikatan yang unik dan kuat. \nTapi mereka tiba-tiba menemukan diri mereka di jalur\nGodzilla yang marah, menyebabkan petak kehancuran \ndi seluruh dunia. Bentrokan epik antara dua raksasa \nitu — yang dipicu oleh kekuatan tak terlihat — \nhanyalah awal dari misteri yang terletak jauh di \ndalam inti Bumi.\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        judul6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel36.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel36.setText("SENIN-KAMIS               JUMAT           SABTU-MINGGU");

        jLabel37.setBackground(new java.awt.Color(0, 255, 102));
        jLabel37.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel37.setText("       40.000                          50.000                         65.000");

        javax.swing.GroupLayout judul6Layout = new javax.swing.GroupLayout(judul6);
        judul6.setLayout(judul6Layout);
        judul6Layout.setHorizontalGroup(
            judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(judul6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        judul6Layout.setVerticalGroup(
            judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul6Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttongodzillaselasa.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillaselasa.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillaselasa.setText("Selasa, 2021-06-22 12:00");
        buttongodzillaselasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillaselasaMouseClicked(evt);
            }
        });
        buttongodzillaselasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillaselasaActionPerformed(evt);
            }
        });

        buttongodzillarabu.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillarabu.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillarabu.setText("Rabu, 2021-06-23 12:00");
        buttongodzillarabu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillarabuMouseClicked(evt);
            }
        });
        buttongodzillarabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillarabuActionPerformed(evt);
            }
        });

        buttongodzillakamis.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillakamis.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillakamis.setText("Kamis, 2021-06-24 12:00");
        buttongodzillakamis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillakamisMouseClicked(evt);
            }
        });
        buttongodzillakamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillakamisActionPerformed(evt);
            }
        });

        buttongodzillajumat.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillajumat.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillajumat.setText("Jumat, 2021-06-25 12:00");
        buttongodzillajumat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillajumatMouseClicked(evt);
            }
        });
        buttongodzillajumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillajumatActionPerformed(evt);
            }
        });

        buttongodzillasabtu.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillasabtu.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillasabtu.setText("Sabtu, 2021-06-26 12:00");
        buttongodzillasabtu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillasabtuMouseClicked(evt);
            }
        });
        buttongodzillasabtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillasabtuActionPerformed(evt);
            }
        });

        buttongodzillaminggu.setBackground(new java.awt.Color(204, 204, 204));
        buttongodzillaminggu.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        buttongodzillaminggu.setText("Minggu, 2021-06-27 12:00");
        buttongodzillaminggu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttongodzillamingguMouseClicked(evt);
            }
        });
        buttongodzillaminggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongodzillamingguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(judul6, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttongodzillasenin, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttongodzillajumat, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttongodzillasabtu, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttongodzillaselasa, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttongodzillarabu, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttongodzillakamis, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttongodzillaminggu, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttongodzillasenin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttongodzillaselasa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttongodzillarabu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttongodzillakamis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttongodzillasabtu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttongodzillajumat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttongodzillaminggu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void buttongodzillaseninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillaseninMouseClicked

    }//GEN-LAST:event_buttongodzillaseninMouseClicked

    private void buttongodzillaseninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillaseninActionPerformed

        KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Senin";
        tanggal="2021-06-21";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillaseninActionPerformed

    private void buttongodzillaselasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillaselasaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttongodzillaselasaMouseClicked

    private void buttongodzillaselasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillaselasaActionPerformed
        KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Selasa";
        tanggal="2021-06-22";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillaselasaActionPerformed

    private void buttongodzillarabuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillarabuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttongodzillarabuMouseClicked

    private void buttongodzillarabuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillarabuActionPerformed
        KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Rabu";
        tanggal="2021-06-23";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillarabuActionPerformed

    private void buttongodzillakamisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillakamisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttongodzillakamisMouseClicked

    private void buttongodzillakamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillakamisActionPerformed
        KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Kamis";
        tanggal="2021-06-24";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillakamisActionPerformed

    private void buttongodzillajumatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillajumatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttongodzillajumatMouseClicked

    private void buttongodzillajumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillajumatActionPerformed
       KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Jumat";
        tanggal="2021-06-25";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillajumatActionPerformed

    private void buttongodzillasabtuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillasabtuMouseClicked
        
    }//GEN-LAST:event_buttongodzillasabtuMouseClicked

    private void buttongodzillasabtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillasabtuActionPerformed
        KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Sabtu";
        tanggal="2021-06-26";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillasabtuActionPerformed

    private void buttongodzillamingguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttongodzillamingguMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttongodzillamingguMouseClicked

    private void buttongodzillamingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongodzillamingguActionPerformed
        KursiStudioGK godzilla = new KursiStudioGK();
        godzilla.setVisible(true);
        godzilla.pack();
        godzilla.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="Godzilla VS Kong";
        hari="Minggu";
        tanggal="2021-06-27";
        jam="12:00";

        KursiStudioGK.tf_namafilm.setText(film);
        KursiStudioGK.tf_hari.setText(hari);
        KursiStudioGK.tf_tanggal.setText(tanggal);
        KursiStudioGK.tf_jam.setText(jam);
    }//GEN-LAST:event_buttongodzillamingguActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailGodzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailGodzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailGodzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailGodzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailGodzilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttongodzillajumat;
    public static javax.swing.JButton buttongodzillakamis;
    public static javax.swing.JButton buttongodzillaminggu;
    public static javax.swing.JButton buttongodzillarabu;
    public static javax.swing.JButton buttongodzillasabtu;
    public static javax.swing.JButton buttongodzillaselasa;
    public static javax.swing.JButton buttongodzillasenin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel judul6;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
