/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasibookingtiket;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // center form 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        kolomusername = new javax.swing.JTextField();
        labelmembuatakun = new javax.swing.JLabel();
        kolompassword = new javax.swing.JPasswordField();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        iconusername = new javax.swing.JLabel();
        iconpassword = new javax.swing.JLabel();
        tombollogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CINEMA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 80, 250, 50);

        kolomusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kolomusername.setForeground(new java.awt.Color(153, 153, 153));
        kolomusername.setText("username");
        kolomusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kolomusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kolomusernameFocusLost(evt);
            }
        });
        kolomusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomusernameActionPerformed(evt);
            }
        });
        jPanel1.add(kolomusername);
        kolomusername.setBounds(180, 170, 325, 50);

        labelmembuatakun.setBackground(new java.awt.Color(255, 255, 255));
        labelmembuatakun.setFont(new java.awt.Font("YouYuan", 0, 18)); // NOI18N
        labelmembuatakun.setForeground(new java.awt.Color(255, 255, 255));
        labelmembuatakun.setText("Don't Have Account? Register Now");
        labelmembuatakun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelmembuatakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelmembuatakunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelmembuatakunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelmembuatakunMouseExited(evt);
            }
        });
        jPanel1.add(labelmembuatakun);
        labelmembuatakun.setBounds(190, 430, 288, 21);

        kolompassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kolompassword.setText("password");
        kolompassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kolompasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kolompasswordFocusLost(evt);
            }
        });
        jPanel1.add(kolompassword);
        kolompassword.setBounds(180, 260, 325, 50);

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(570, 50, 32, 29);

        minimize.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(530, 50, 34, 29);

        iconusername.setBackground(new java.awt.Color(255, 255, 255));
        iconusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/FIXPASS.png"))); // NOI18N
        iconusername.setOpaque(true);
        jPanel1.add(iconusername);
        iconusername.setBounds(100, 170, 54, 50);
        // set icon to the jlabel
        iconusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/FIXUSER1.jpg")));

        iconpassword.setBackground(new java.awt.Color(255, 255, 255));
        iconpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/FIXUSER1.jpg"))); // NOI18N
        iconpassword.setOpaque(true);
        jPanel1.add(iconpassword);
        iconpassword.setBounds(100, 260, 50, 50);
        // set icon to the jlabel
        iconpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/FIXPASS.png")));

        tombollogin.setBackground(new java.awt.Color(153, 153, 153));
        tombollogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tombollogin.setText("Login");
        tombollogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombollogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolloginMouseExited(evt);
            }
        });
        tombollogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolloginActionPerformed(evt);
            }
        });
        jPanel1.add(tombollogin);
        tombollogin.setBounds(180, 350, 325, 58);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/bioskop2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 520);
        jLabel1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void labelmembuatakunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmembuatakunMouseExited

        Border label_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray);
        labelmembuatakun.setBorder(null);
    }//GEN-LAST:event_labelmembuatakunMouseExited

    private void labelmembuatakunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmembuatakunMouseEntered

        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        labelmembuatakun.setBorder(label_border);
    }//GEN-LAST:event_labelmembuatakunMouseEntered

    private void labelmembuatakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmembuatakunMouseClicked
        // menuju ke registration 
        Registration rf = new Registration();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelmembuatakunMouseClicked

    private void tombolloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolloginActionPerformed

        PreparedStatement st;
        ResultSet rs;

        // mengambil username dan password
        String username = kolomusername.getText();
        String password = String.valueOf(kolompassword.getPassword());

        //query select untuk memeriksa apakah nama pengguna dan kata sandi ada di database
        String query = "SELECT * FROM tb_users WHERE username = ? AND PASSWORD = ?";

        //tunjukkan pesan jika username atau bidang password kosong
        if(username.trim().equals("username"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);

        }
        else if(password.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }
        else{
            try {
                //memanggil class javatomysql
                st = javatomysql.getConnection().prepareStatement(query);
                // memanggil inputan username dan password
                st.setString(1, username);
                st.setString(2, password);
                rs = st.executeQuery();

                if(rs.next()){
                    // jika login berhasil, maka akan menuju ke form menu
                    MoviesForm mf = new MoviesForm();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
                else{
                    // pesan error
                    JOptionPane.showMessageDialog(null, "Invalid Username or Password", "Login Error", 2);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombolloginActionPerformed

    private void tombolloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolloginMouseExited
        // set background
        tombollogin.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_tombolloginMouseExited

    private void tombolloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolloginMouseEntered
        // set background
        tombollogin.setBackground(new Color(112, 128, 145));
    }//GEN-LAST:event_tombolloginMouseEntered

    private void kolompasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kolompasswordFocusLost
        // jika kolom password sama dengan "password" atau kosong
        // kita akan menyetel teks "password" 

        // mengambil teks password
        String pass = String.valueOf(kolompassword.getPassword());

        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password"))
        {
            kolompassword.setText("password");
            kolompassword.setForeground(new Color(153,153,153));
        }

        // hapus garis perbatasan
        iconpassword.setBorder(null);
    }//GEN-LAST:event_kolompasswordFocusLost

    private void kolompasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kolompasswordFocusGained

        // mengambil teks password
        String pass = String.valueOf(kolompassword.getPassword());

        if(pass.trim().toLowerCase().equals("password"))
        {
            kolompassword.setText("");
            kolompassword.setForeground(Color.black);
        }

        // set garis batas hitam ke ikon password
        Border icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconpassword.setBorder(icon);
    }//GEN-LAST:event_kolompasswordFocusGained

    private void kolomusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kolomusernameFocusLost
        // jika kolom teks sama dengan "username" atau kosong
        // akan disetel teks "username" di kolom

        if(kolomusername.getText().trim().equals("") || kolomusername.getText().trim().toLowerCase().equals("username"))
        {
            kolomusername.setText("username");
            kolomusername.setForeground(new Color(153,153,153));
        }

        // hapus garis perbatasan
        iconusername.setBorder(null);
    }//GEN-LAST:event_kolomusernameFocusLost

    private void kolomusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kolomusernameFocusGained
        // kosongkan kolom teks jika teksnya "username"
        if(kolomusername.getText().trim().toLowerCase().equals("username"))
        {
            kolomusername.setText("");
            kolomusername.setForeground(Color.black);
        }

        // set garis batas hitam ke ikon username
        Border icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconusername.setBorder(icon);
    }//GEN-LAST:event_kolomusernameFocusGained

    private void kolomusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel iconpassword;
    private javax.swing.JLabel iconusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField kolompassword;
    private javax.swing.JTextField kolomusername;
    private javax.swing.JLabel labelmembuatakun;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton tombollogin;
    // End of variables declaration//GEN-END:variables
}
