
package aplikasibookingtiket;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration_Form
     */
    public Registration() {
        initComponents();
        
        // Agar Output Berada di tengah
        this.setLocationRelativeTo(null);
        
        
        // Membuat Garis Batasan Hitam pada Minimize dan Close
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(label_border);
        close.setBorder(label_border);
        
        //Membuat garis batasan pada label login
        Border label_login_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray);
        labellogin.setBorder(label_login_border);
        
        //Membuat Garis Batasan Hitam pada kolom username dan kolom password
        Border fieldborder = BorderFactory.createMatteBorder(1, 5, 5, 1, Color.white);
        kolomfullname.setBorder(fieldborder);
        kolomusername.setBorder(fieldborder);
        kolompassword.setBorder(fieldborder);
        kolomconfirmpassword.setBorder(fieldborder);
        
        // buat grup tombol untuk radiobuttunos (male and female)
        ButtonGroup bg = new ButtonGroup();
        bg.add(tombolmale);
        bg.add(tombolfemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labellogin = new javax.swing.JLabel();
        tombolfemale = new javax.swing.JRadioButton();
        tombolmale = new javax.swing.JRadioButton();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        kolomfullname = new javax.swing.JTextField();
        kolomusername = new javax.swing.JTextField();
        kolompassword = new javax.swing.JPasswordField();
        kolomconfirmpassword = new javax.swing.JPasswordField();
        tombolregister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kolomphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        labellogin.setBackground(new java.awt.Color(255, 255, 255));
        labellogin.setFont(new java.awt.Font("YouYuan", 0, 18)); // NOI18N
        labellogin.setForeground(new java.awt.Color(255, 255, 255));
        labellogin.setText("Already Have an Account? Login");
        labellogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelloginMouseExited(evt);
            }
        });
        jPanel1.add(labellogin);
        labellogin.setBounds(240, 540, 270, 21);

        tombolfemale.setBackground(new java.awt.Color(255, 255, 255));
        tombolfemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tombolfemale.setForeground(new java.awt.Color(255, 255, 255));
        tombolfemale.setText("Female");
        jPanel1.add(tombolfemale);
        tombolfemale.setBounds(420, 420, 87, 31);

        tombolmale.setBackground(new java.awt.Color(255, 255, 255));
        tombolmale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tombolmale.setForeground(new java.awt.Color(255, 255, 255));
        tombolmale.setText("Male");
        jPanel1.add(tombolmale);
        tombolmale.setBounds(340, 420, 69, 31);

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(650, 80, 32, 29);

        minimize.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(610, 80, 34, 29);

        kolomfullname.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(kolomfullname);
        kolomfullname.setBounds(340, 170, 210, 29);

        kolomusername.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(kolomusername);
        kolomusername.setBounds(340, 220, 210, 29);

        kolompassword.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(kolompassword);
        kolompassword.setBounds(340, 270, 210, 29);

        kolomconfirmpassword.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(kolomconfirmpassword);
        kolomconfirmpassword.setBounds(340, 320, 210, 29);

        tombolregister.setBackground(new java.awt.Color(153, 153, 153));
        tombolregister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tombolregister.setText("Register");
        tombolregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolregisterMouseExited(evt);
            }
        });
        tombolregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolregisterActionPerformed(evt);
            }
        });
        jPanel1.add(tombolregister);
        tombolregister.setBounds(220, 470, 325, 58);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CINEMA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 80, 170, 50);

        kolomphone.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        kolomphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomphoneKeyTyped(evt);
            }
        });
        jPanel1.add(kolomphone);
        kolomphone.setBounds(340, 370, 210, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password  :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 320, 168, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password              :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 270, 169, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone                  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 370, 167, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender                :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 420, 165, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username             :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 220, 169, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name             :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 170, 169, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/bioskop2big.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 720, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolomphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomphoneKeyTyped

        // izinkan hanya menginput angka
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_kolomphoneKeyTyped

    private void tombolregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolregisterActionPerformed
        // mengambil data
        String fname = kolomfullname.getText();
        String username = kolomusername.getText();
        String pass = String.valueOf(kolompassword.getPassword());
        String confirm = String.valueOf(kolomconfirmpassword.getPassword());
        String phone = kolomphone.getText();
        String gender = "Male";

        if(tombolfemale.isSelected()){
            gender = "Female";
        }

        // periksa apakah datanya kosong
        if(validasikolom())
        {
            // periksa apakah username sudah ada dalam database
            if(!checkusername(username))
            {
                PreparedStatement ps;
                ResultSet rs;
                String register_user_query = "INSERT INTO tb_users (full_name, username, password, phone, gender) VALUES (?,?,?,?,?)";

                try {
                    // memanggil class javatomysql
                    ps = javatomysql.getConnection().prepareStatement(register_user_query);
                    // mengambil inputan
                    ps.setString(1, fname);
                    ps.setString(2, username);
                    ps.setString(3, pass);
                    ps.setString(4, phone);
                    ps.setString(5, gender);

                    if(ps.executeUpdate()!=0){
                        // pesan sukses
                        JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                    }
                    else{
                        // pesan error
                        JOptionPane.showMessageDialog(null, "Error : Check Your Information");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_tombolregisterActionPerformed

    private void tombolregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolregisterMouseExited
        // set background
        tombolregister.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_tombolregisterMouseExited

    private void tombolregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolregisterMouseEntered
        // set background
        tombolregister.setBackground(new Color(112, 128, 145));
    }//GEN-LAST:event_tombolregisterMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void labelloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseExited

        Border label_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray);
        labellogin.setBorder(null);
    }//GEN-LAST:event_labelloginMouseExited

    private void labelloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseEntered

        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        labellogin.setBorder(label_border);
    }//GEN-LAST:event_labelloginMouseEntered

    private void labelloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelloginMouseClicked
        // menuju ke class login
        Login lf = new Login();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelloginMouseClicked

    // buat fungsi untuk memverifikasi kolom kosong
    public boolean validasikolom()
    {   // mengambil data
        String fname = kolomfullname.getText();
        String uname = kolomusername.getText();
        String phone = kolomphone.getText();
        String pass = String.valueOf(kolompassword.getPassword());
        String confirm = String.valueOf(kolomconfirmpassword.getPassword());
        
        // periksa kolom kosong
        if(fname.trim().equals("") || uname.trim().equals("") || phone.trim().equals("") 
            || pass.trim().equals("") || confirm.trim().equals(""))
        { // jika kosong
           JOptionPane.showMessageDialog(null, "One Or More Field Are Empty","Empty Fields",2);
           return false;
        }
        
        // periksa apakah data password dan confirm password itu sama
        // jika salah
        else if(!pass.equals(confirm))
        {
            JOptionPane.showMessageDialog(null, "Password Doesn't Match","Condirm Password",2);
            return false;
        }
        
        // jika benar
        else{
            return true;
        }
    }
    
    // buat fungsi untuk memeriksa apakah nama pengguna yang dimasukkan sudah ada di database
    public boolean checkusername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM tb_users WHERE username = ?";
        
        try {
            // memanggil class javatomysql
            st = javatomysql.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            // jika akun sudah ada dalam database
            if(rs.next())
            {
                username_exist = true;
                // pesan error
                JOptionPane.showMessageDialog(null, "This User is Already Taken, Choose Another One", "Username Failed", 2);  
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField kolomconfirmpassword;
    private javax.swing.JTextField kolomfullname;
    private javax.swing.JPasswordField kolompassword;
    private javax.swing.JTextField kolomphone;
    private javax.swing.JTextField kolomusername;
    private javax.swing.JLabel labellogin;
    private javax.swing.JLabel minimize;
    private javax.swing.JRadioButton tombolfemale;
    private javax.swing.JRadioButton tombolmale;
    private javax.swing.JButton tombolregister;
    // End of variables declaration//GEN-END:variables
}
